# -*- coding: utf-8 -*-
"""myfirstalgoritm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIvEaJR4U547nupU7YLnWVCKXyydQwly
"""

valor1=0
valor2=0
operacao=0
i=0
opcao='Sim'

while opcao == 'Sim':
  valor1 = int(input('Digite o primeiro valor: '))
  operacao = input('Digite o sinal da operação: ')
  valor2 = int(input('Digite o segundo valor: '))
  if operacao == '+':
    print('Sua soma resultou em: ', valor1+valor2)
  elif operacao == '-':
    print('Sua subtração resultou em: ', valor1-valor2)
  elif operacao == '*':
    print('Sua multiplicação resultou em: ', valor1*valor2)
  elif operacao == '/':
    print('Sua divisão resultou em: ', valor1/valor2)
  else:
    print('Você não digitou um operador válido!')
  opcao = input('Deseja continuar? Digite apenas Sim ou Não ')
else:
  print('Fim da operação!')